name: Build dnEditor

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  SOLUTION_FILE: dnEditor.sln
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: '7.0.x'
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Install .NET Framework 4.0
      shell: powershell
      run: |
        # 下载 .NET Framework 4.0 Targeting Pack
        $url = "https://download.microsoft.com/download/9/5/A/95A9616B-7A37-4AF6-BC36-D6EA96C8DAAE/dotNetFx40_Full_x86_x64.exe"
        $output = "dotNetFx40_Full.exe"
        
        Write-Host "Downloading .NET Framework 4.0..."
        Invoke-WebRequest -Uri $url -OutFile $output
        
        Write-Host "Installing .NET Framework 4.0..."
        Start-Process -FilePath $output -ArgumentList "/q /norestart" -Wait
        
        # 安装 .NET Framework 4.0 Targeting Pack
        choco install netfx-4.0.3-devpack --yes --force --execution-timeout=3600

    - name: Initialize submodules
      run: |
        git submodule update --init --recursive

    - name: Update project files
      shell: powershell
      run: |
        $references = "<ItemGroup><Reference Include=`"System`" /><Reference Include=`"System.Core`" /><Reference Include=`"System.Data`" /><Reference Include=`"System.Drawing`" /><Reference Include=`"System.Windows.Forms`" /><Reference Include=`"System.Xml`" /></ItemGroup></Project>"
        Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
          $content = Get-Content $_.FullName -Raw
          if (-not ($content -match "<Reference Include=`"System`"")) {
            $content = $content -replace '</Project>', $references
            Set-Content -Path $_.FullName -Value $content
          }
        }

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '5.x'

    - name: Restore NuGet packages
      run: |
        nuget restore ${{ env.SOLUTION_FILE }}

    - name: Build with MSBuild
      run: |
        msbuild ${{ env.SOLUTION_FILE }} `
          /p:Configuration=${{ env.BUILD_CONFIGURATION }} `
          /p:Platform="Any CPU" `
          /p:TargetFrameworkVersion=v4.0 `
          /t:Rebuild `
          /m `
          /p:AllowUnsafeBlocks=true `
          /p:WarningLevel=0

    - name: Create output directory
      run: mkdir publish

    - name: Copy build outputs
      shell: powershell
      run: |
        Copy-Item "dnEditor\bin\${{ env.BUILD_CONFIGURATION }}\*" -Destination "publish" -Recurse

    - name: Create ZIP archive
      shell: pwsh
      run: |
        Compress-Archive -Path publish\* -DestinationPath dnEditor-win-x64.zip -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: dnEditor-Windows
        path: dnEditor-win-x64.zip
        if-no-files-found: error

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        
    - name: Display structure of downloaded files
      run: ls -R artifacts/

    - name: Prepare release files
      run: |
        mkdir release_files
        find artifacts -name "*.zip" -exec cp {} release_files/ \;
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: release_files/*.zip
        generate_release_notes: true
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Release ${{ github.ref_name }}
        body: |
          ## dnEditor Release ${{ github.ref_name }}
          
          ### 功能特点
          - 基于 dnlib 的 .NET 程序集编辑器
          - 支持 ILSpy 反编译器集成
          - 提供成员创建和删除支持
          - 包含搜索功能
          
          ### 系统要求
          - Windows x64 系统
          - .NET Framework 4.0 或更高版本
          
          ### 更新内容
          - 优化构建配置
          - 改进性能和稳定性
          - 修复已知问题
          
          ### 安装说明
          1. 下载 dnEditor-win-x64.zip
          2. 解压到任意目录
          3. 运行 dnEditor.exe

    - name: Check Release Status
      if: always()
      run: |
        echo "Release creation status: ${{ job.status }}"
        if [ "${{ job.status }}" != "success" ]; then
          echo "Release creation failed. Please check the error messages above."
          exit 1
        fi
