name: Build dnEditor

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  SOLUTION_FILE: dnEditor.sln
  BUILD_CONFIGURATION: Release
  DOTNET_VERSION: '7.0.x'
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Install .NET Framework Developer Pack
      shell: powershell
      run: |
        Write-Host "Installing .NET Framework 4.0 Developer Pack..."
        choco install netfx-4.0.3-devpack -y
        
        Write-Host "Installing Windows SDK..."
        choco install windows-sdk-7.1 -y

    - name: Initialize submodules
      run: |
        git submodule update --init --recursive

    - name: Create Reference Include File
      shell: powershell
      run: |
        $referenceContent = @"
<ItemGroup>
  <Reference Include="System" />
  <Reference Include="System.Core" />
  <Reference Include="System.Data" />
  <Reference Include="System.Drawing" />
  <Reference Include="System.Windows.Forms" />
  <Reference Include="System.Xml" />
</ItemGroup>
</Project>
"@
        Set-Content -Path "references.txt" -Value $referenceContent
        
    - name: Update project files
      shell: powershell
      run: |
        $referenceContent = Get-Content "references.txt" -Raw
        Get-ChildItem -Recurse -Filter *.csproj | ForEach-Object {
          $content = Get-Content $_.FullName -Raw
          if (-not ($content -match "<Reference Include=`"System`"")) {
            $content = $content -replace '</Project>', $referenceContent
            Set-Content -Path $_.FullName -Value $content
          }
        }

    - name: Restore NuGet packages
      run: |
        nuget restore ${{ env.SOLUTION_FILE }}

    - name: Build with MSBuild
      run: |
        msbuild ${{ env.SOLUTION_FILE }}
